services:
  - type: web
    name: metabird-backend
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    autoDeploy: true

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: VAULT_URI
        sync: false
      - key: VAULT_TOKEN
        sync: false

      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
