spring:
  config:
    activate:
      on-profile: dev

app:
  mongo:
    uri: ${MONGO_URI:mongodb://localhost:27017/metabird}
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  redis:
    prefix: ${REDIS_PREFIX}
  upstash:
    url: ${UPSTASH_URL}
    token: ${UPSTASH_TOKEN}
  salesforce:
    production: ${SALESFORCE_PRODUCTION}
    sandbox: ${SALESFORCE_SANDBOX}
